import type { Metadata } from 'next'
import './globals.css'
import { ConvexClientProvider } from '@/providers/ConvexClientProvider'
import { SignInButton, SignedIn, SignedOut } from '@clerk/nextjs'
import { Toaster } from '@/components/ui/sonner'
import { ModalProvider } from '@/providers/modal-provider'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body>
				<ConvexClientProvider>
					<header>
						<SignedOut>
							<SignInButton />
						</SignedOut>
						<SignedIn>{/* <UserButton /> */}</SignedIn>
					</header>
					<main>
						<Toaster />
						<ModalProvider />
						{children}
					</main>
				</ConvexClientProvider>
			</body>
		</html>
	)
}
